{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "video-poc.serviceAccountName" . }}
  labels:
    {{- include "video-poc.labels" . | nindent 4 }}
{{- end }}
